### ISSUE TITLE
Potential optimization to be made in observer.js / fire

### ISSUE THREAD

**Issue by bsergean** [satori-com/satori-rtm-sdk-js#1]
While running the Chrome inspector I noticed this performance warnings: "Not optimized: Bad Value context for argument value", and I wonder if anything can be done about it.

![screen shot 2017-04-06 at 2 29 40 pm](https://cloud.githubusercontent.com/assets/11857745/24776437/aa3826a0-1ad5-11e7-9504-870a267cb32b.png)

![screen shot 2017-04-06 at 2 29 06 pm](https://cloud.githubusercontent.com/assets/11857745/24776443/ae88d84e-1ad5-11e7-80b5-4fc604997db7.png)

I found this link by googling "Not optimized: Bad Value context for argument value" -> https://github.com/GoogleChrome/devtools-docs/issues/53

Thanks !

**Comment by bsergean** [comment]
Potential fix on that linked page:

![screen shot 2017-04-06 at 3 46 43 pm](https://cloud.githubusercontent.com/assets/11857745/24778588/4d19e9f8-1ae0-11e7-8797-2318a521591a.png)

**Comment by satori-avasenin** [comment]
Should be fixed by this commit https://github.com/satori-com/satori-rtm-sdk-js/commit/0ae2291dd7dd95b0d44055336ec6911d12f756e6
